edgar.ezuicron.list:
    path: /cron/list
    defaults:
        _controller: 'EdgarEzUICronBundle:Cron:list'

edgar.ezuicron.update:
    path: /cron/update/{alias}
    defaults:
        alias: null
        _controller: 'EdgarEzUICronBundle:Cron:update'
