edgar.ezuicron.list:
    path: /list
    defaults:
        _controller: 'EdgarEzUICronBundle:Cron:list'

edgar.ezuicron.update:
    path: /update/{alias}
    defaults:
        _controller: 'EdgarEzUICronBundle:Cron:update'

edgar.ezuicron.reset:
    path: /reset/{alias}
    defaults:
        _controller: 'EdgarEzUICronBundle:Cron:reset'
