edgar.ezuicron.list:
    path: /list
    defaults:
        _controller: 'Edgar\EzUICronBundle\Controller\CronController::listAction'

edgar.ezuicron.update:
    path: /update/{alias}
    defaults:
        _controller: 'Edgar\EzUICronBundle\Controller\CronController::updateAction'

edgar.ezuicron.reset:
    path: /reset/{alias}
    defaults:
        _controller: 'Edgar\EzUICronBundle\Controller\CronController::resetAction'
