imports:
    - { resource: controllers.yml }
    - { resource: dashboard.yml }
    - { resource: menu.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUICronBundle\Service\EzCronService:
        public: true

    Edgar\EzUICronBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
          - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }

    Edgar\EzUICron\Form\SubmitHandler:
        public: true
        arguments:
            $notificationHandler: "@EzSystems\\EzPlatformAdminUi\\Notification\\FlashBagNotificationHandler"
